trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: shopify

steps:
- task: Checkout@1
  inputs:
    repository: 'self'

- script: |
    curl -s https://shopify.github.io/themekit/scripts/install.sh | bash
  displayName: 'Install Shopify Theme Kit'

- script: |
    theme deploy --env production
  displayName: 'Deploy Theme'
  env:
    SHOPIFY_API_KEY: $(SHOPIFY_API_KEY)
    SHOPIFY_API_PASSWORD: $(SHOPIFY_API_PASSWORD)
    SHOPIFY_STORE: $(SHOPIFY_STORE)
