trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseNode@1
  inputs:
    versionSpec: '14.x'
  displayName: 'Use Node.js 14.x'

- script: |
    npm install -g shopify-cli
  displayName: 'Install Shopify CLI'

- script: |
    # Login to Shopify
    shopify login --store $(SHOPIFY_STORE) --api-key $(SHOPIFY_API_KEY) --password $(SHOPIFY_API_PASSWORD)
    # Deploy theme
    shopify theme push --theme <YOUR_THEME_ID> --env production
  displayName: 'Deploy Shopify Theme'
  env:
    SHOPIFY_API_KEY: 8b37ae40f7472537d6904e8589fb4346
    SHOPIFY_API_PASSWORD: 656447d8c0683221df8f6eb5841e1df1
    SHOPIFY_STORE: quick-start-c4c85419.myshopify.com
